# curl localhost:8080/api/v1/messages
GET localhost:8080/api/v1/messages
Content-Type: application/json
Accept:: application/json

###

# curl localhost:8080/api/v1/messages -d'{"message": "hello"}' -H'content-type: application/json'
POST localhost:8080/api/v1/messages
Content-Type: application/json
Accept:: application/json

{
  "message": "hello"
}

###

# curl localhost:8080/api/v1/messages -d'{"message": "world"}' -H'content-type: application/json'
POST localhost:8080/api/v1/messages
Content-Type: application/json
Accept:: application/json

{
  "message": "world"
}

###

# curl localhost:8080/api/v1/messages
GET localhost:8080/api/v1/messages
Content-Type: application/json
Accept:: application/json

###

# curl localhost:8080/api/v1/messages
GET http://localhost:8080/api/v1/messages/{{uuid}}
Content-Type: application/json
Accept:: application/json

###
